package io.searchbox.indices;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractMultiIndexActionBuilder;

public class ClearCache extends GenericResultAbstractAction {

  protected ClearCache(ClearCache.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  @Override
  protected String buildURI() {
    return super.buildURI() + "/_cache/clear";
  }
  public String getRestMethodName() {
    return "POST";
  }

  public static class Builder extends AbstractMultiIndexActionBuilder<ClearCache, ClearCache.Builder> {
    public ClearCache.Builder filter(boolean filter) {
      setParameter("filter", filter);
      return this;
    }
    public ClearCache.Builder fieldData(boolean fieldData) {
      setParameter("field_data", fieldData);
      return this;
    }
    public ClearCache.Builder bloom(boolean bloom) {
      setParameter("bloom", bloom);
      return this;
    }
    @Override
    public ClearCache build() {
      return new ClearCache(this);
    }
  }
}
