package io.searchbox.indices;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractAction;

public class CloseIndex extends GenericResultAbstractAction {

  protected CloseIndex(CloseIndex.Builder builder) {
    super(builder);
    this.indexName = builder.index;
    setURI(buildURI());
  }
  @Override
  protected String buildURI() {
    return super.buildURI() + "/_close";
  }
  @Override
  public String getRestMethodName() {
    return "POST";
  }
  public static class Builder extends AbstractAction.Builder<CloseIndex, CloseIndex.Builder> {
    private String index;
    public Builder(String index) {
      this.index = index;
    }
    @Override
    public CloseIndex build() {
      return new CloseIndex(this);
    }
  }
}
