package io.searchbox.indices;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractAction;

public class DeleteIndex extends GenericResultAbstractAction {

  protected DeleteIndex(DeleteIndex.Builder builder) {
    super(builder);
    indexName = builder.index;
    typeName = builder.type;
    setURI(buildURI());
  }
  @Override
  public String getRestMethodName() {
    return "DELETE";
  }
  public static class Builder extends AbstractAction.Builder<DeleteIndex, DeleteIndex.Builder> {
    private String index;
    private String type;
    public Builder(String index) {
      this.index = index;
    }
    public DeleteIndex.Builder type(String type) {
      this.type = type;
      return this;
    }
    @Override
    public DeleteIndex build() {
      return new DeleteIndex(this);
    }
  }
}
