package io.searchbox.indices;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractMultiIndexActionBuilder;

public class Flush extends GenericResultAbstractAction {

  protected Flush(Flush.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  @Override
  protected String buildURI() {
    return super.buildURI() + "/_flush";
  }
  @Override
  public String getRestMethodName() {
    return "POST";
  }
  public static class Builder extends AbstractMultiIndexActionBuilder<Flush, Flush.Builder> {
    @Override
    public Flush build() {
      return new Flush(this);
    }
  }
}
