package io.searchbox.indices;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractMultiIndexActionBuilder;
import java.util.Collection;

public class IndicesExists extends GenericResultAbstractAction {

  protected IndicesExists(IndicesExists.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  @Override
  public String getRestMethodName() {
    return "HEAD";
  }
  public static class Builder extends AbstractMultiIndexActionBuilder<IndicesExists, IndicesExists.Builder> {
    public Builder(String index) {
      addIndex(index);
    }
    public Builder(Collection<? extends String> indices) {
      addIndex(indices);
    }
    @Override
    public IndicesExists build() {
      return new IndicesExists(this);
    }
  }
}
