package io.searchbox.indices;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractAction;

public class OpenIndex extends GenericResultAbstractAction {

  protected OpenIndex(OpenIndex.Builder builder) {
    super(builder);
    this.indexName = builder.index;
    setURI(buildURI());
  }
  @Override
  protected String buildURI() {
    return super.buildURI() + "/_open";
  }
  @Override
  public String getRestMethodName() {
    return "POST";
  }
  public static class Builder extends AbstractAction.Builder<OpenIndex, OpenIndex.Builder> {
    private String index;
    public Builder(String index) {
      this.index = index;
    }
    @Override
    public OpenIndex build() {
      return new OpenIndex(this);
    }
  }
}
