package io.searchbox.indices;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractMultiIndexActionBuilder;

public class Refresh extends GenericResultAbstractAction {

  protected Refresh(Refresh.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  @Override
  public String getRestMethodName() {
    return "POST";
  }
  @Override
  protected String buildURI() {
    return super.buildURI() + "/_refresh";
  }
  public static class Builder extends AbstractMultiIndexActionBuilder<Refresh, Refresh.Builder> {
    @Override
    public Refresh build() {
      return new Refresh(this);
    }
  }
}
