package io.searchbox.params;

/*Generated by MPS */


public class SearchType {

  private String value;
  /*package*/ SearchType(String value) {
    this.value = value;
  }
  public String toString() {
    return this.value;
  }
}
