package io.searchbox.snapshot;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractAction;

public abstract class AbstractSnapshotRepositoryAction extends GenericResultAbstractAction {

  private String repositories;
  protected AbstractSnapshotRepositoryAction(AbstractSnapshotRepositoryAction.RepositoryBuilder builder) {
    super(builder);
    this.repositories = builder.getRepositories();
    setURI(buildURI());
  }
  @Override
  protected String buildURI() {
    return super.buildURI() + "/_snapshot/" + repositories;
  }
  public static abstract class RepositoryBuilder<T extends AbstractSnapshotRepositoryAction, K> extends AbstractAction.Builder<T, K> {
    protected abstract String getRepositories();
  }
  public static abstract class SingleRepositoryBuilder<T extends AbstractSnapshotRepositoryAction, K> extends AbstractSnapshotRepositoryAction.RepositoryBuilder<T, K> {
    private String repository;
    public SingleRepositoryBuilder(String repository) {
      this.repository = repository;
    }
    protected String getRepositories() {
      return repository;
    }
  }
}
