package io.searchbox.snapshot;

/*Generated by MPS */


public class CreateSnapshotRepository extends AbstractSnapshotRepositoryAction {

  protected CreateSnapshotRepository(CreateSnapshotRepository.Builder builder) {
    super(builder);
    this.payload = builder.settings;
  }
  @Override
  public String getRestMethodName() {
    return "PUT";
  }
  public static class Builder extends AbstractSnapshotRepositoryAction.SingleRepositoryBuilder<CreateSnapshotRepository, CreateSnapshotRepository.Builder> {
    private Object settings;
    public Builder(String repository) {
      super(repository);
    }
    public CreateSnapshotRepository.Builder settings(Object settings) {
      this.settings = settings;
      return this;
    }
    public CreateSnapshotRepository.Builder verify(boolean verify) {
      return setParameter("verify", verify);
    }
    @Override
    public CreateSnapshotRepository build() {
      return new CreateSnapshotRepository(this);
    }
  }
}
