package io.searchbox.snapshot;

/*Generated by MPS */


public class DeleteSnapshotRepository extends AbstractSnapshotRepositoryAction {

  protected DeleteSnapshotRepository(DeleteSnapshotRepository.Builder builder) {
    super(builder);
  }
  @Override
  public String getRestMethodName() {
    return "DELETE";
  }
  public static class Builder extends AbstractSnapshotRepositoryAction.SingleRepositoryBuilder<DeleteSnapshotRepository, DeleteSnapshotRepository.Builder> {
    public Builder(String repository) {
      super(repository);
    }
    @Override
    public DeleteSnapshotRepository build() {
      return new DeleteSnapshotRepository(this);
    }
  }
}
