package io.searchbox.snapshot;

/*Generated by MPS */

import java.util.Set;
import java.util.LinkedHashSet;
import java.util.Collection;
import org.apache.commons.lang3.StringUtils;

public class GetSnapshotRepository extends AbstractSnapshotRepositoryAction {

  protected GetSnapshotRepository(GetSnapshotRepository.Builder builder) {
    super(builder);
  }
  @Override
  public String getRestMethodName() {
    return "GET";
  }
  public static class Builder extends AbstractSnapshotRepositoryAction.RepositoryBuilder<GetSnapshotRepository, GetSnapshotRepository.Builder> {
    private Set<String> repositories = new LinkedHashSet<String>();
    public Builder() {
    }
    public Builder(String repository) {
      this.repositories.add(repository);
    }
    public Builder(Collection<? extends String> repositories) {
      this.repositories.addAll(repositories);
    }
    public GetSnapshotRepository.Builder addRepository(Collection<? extends String> repositories) {
      this.repositories.addAll(repositories);
      return this;
    }
    @Override
    public GetSnapshotRepository build() {
      return new GetSnapshotRepository(this);
    }
    @Override
    protected String getRepositories() {
      if (repositories.isEmpty()) {
        return "_all";
      } else {
        return StringUtils.join(repositories, ",");
      }
    }
  }
}
