package io.searchbox.snapshot;

/*Generated by MPS */


public class GetSnapshot extends AbstractSnapshotAction {

  protected GetSnapshot(GetSnapshot.Builder builder) {
    super(builder);
  }
  @Override
  public String getRestMethodName() {
    return "GET";
  }
  public static class Builder extends AbstractSnapshotAction.MultipleSnapshotBuilder<GetSnapshot, GetSnapshot.Builder> {
    public Builder(String repository) {
      super(repository);
    }
    @Override
    public GetSnapshot build() {
      return new GetSnapshot(this);
    }
  }
}
