package io.searchbox.snapshot;

/*Generated by MPS */


public class SnapshotStatus extends AbstractSnapshotAction {

  protected SnapshotStatus(SnapshotStatus.Builder builder) {
    super(builder);
  }
  @Override
  protected String buildURI() {
    return super.buildURI() + "/_status";
  }
  @Override
  public String getRestMethodName() {
    return "GET";
  }
  public static class Builder extends AbstractSnapshotAction.MultipleSnapshotBuilder<SnapshotStatus, SnapshotStatus.Builder> {
    public Builder(String repository) {
      super(repository);
    }
    @Override
    public SnapshotStatus build() {
      return new SnapshotStatus(this);
    }
  }
}
