package io.searchbox.client.http.apache;

/*Generated by MPS */

import org.apache.http.client.methods.HttpEntityEnclosingRequestBase;
import java.net.URI;
import org.apache.http.client.methods.HttpDelete;

public class HttpDeleteWithEntity extends HttpEntityEnclosingRequestBase {

  public HttpDeleteWithEntity() {
    super();
  }
  public HttpDeleteWithEntity(URI uri) {
    super();
    setURI(uri);
  }
  public HttpDeleteWithEntity(String uri) {
    super();
    setURI(URI.create(uri));
  }
  @Override
  public String getMethod() {
    return HttpDelete.METHOD_NAME;
  }
}
