package io.searchbox.client;

/*Generated by MPS */

import io.searchbox.action.Action;
import java.io.IOException;
import java.util.Set;

/**
 * @author Dogukan Sonmez
 */
public interface JestClient {
  public <T extends JestResult> T execute(Action<T> clientRequest) throws IOException;
  public <T extends JestResult> void executeAsync(Action<T> clientRequest, JestResultHandler<? super T> jestResultHandler);
  public void shutdownClient();
  public void setServers(Set<String> servers);
}
