package io.searchbox.client;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.Component;
import java.awt.Color;
import java.awt.FlowLayout;

public class UserInterface {

  private JFrame mainFrame;
  private JLabel indexLable;
  private JLabel statusLable;
  private JPanel controlPanel;
  private JLabel msglabel;
  private JTextField indexField;
  private GridBagLayout g;
  private GridBagConstraints c;

  public UserInterface() {
    prepareGUI();
  }

  public static void main(String[] args) {
    UserInterface userInterface = new UserInterface();
  }

  private void prepareGUI() {
    mainFrame = new JFrame("Jest Client");
    mainFrame.setSize(400, 400);
    mainFrame.setLayout(new GridLayout(3, 1));
    mainFrame.addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent windowEvent) {
        System.exit(0);
      }
    });

    controlPanel = new JPanel();
    g = new GridBagLayout();
    c = new GridBagConstraints();

    controlPanel.setLayout(g);
    indexLable = new JLabel("Index", JLabel.LEFT);
    c.gridx = 0;
    c.gridy = 0;
    controlPanel.add(indexLable, c);

    indexField = new JTextField(40);
    indexField.setHorizontalAlignment(JTextField.LEFT);
    c.gridx = 0;
    c.gridy = 1;
    controlPanel.add(indexField, c);


    controlPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
    mainFrame.add(controlPanel);
    mainFrame.setVisible(true);

  }

  private void showJPanelDemo() {
    indexLable.setText("Index");
    indexLable.setSize(400, 200);
    JPanel panel = new JPanel();
    panel.setBackground(Color.magenta);
    panel.setLayout(new FlowLayout());
    panel.add(msglabel);

    controlPanel.add(panel);
    mainFrame.setVisible(true);
  }
}
