package io.searchbox.core.search.aggregation;

/*Generated by MPS */

import com.google.gson.JsonObject;
import java.util.List;

public abstract class BucketAggregation extends Aggregation {

  public BucketAggregation(String name, JsonObject root) {
    super(name, root);
  }
  /*package*/ abstract List<? extends Bucket> getBuckets();
}
