package io.searchbox.core.search.aggregation;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

public class HistogramAggregation extends BucketAggregation {

  public static final String TYPE = "histogram";
  private List<HistogramAggregation.Histogram> histograms = new LinkedList<HistogramAggregation.Histogram>();
  public HistogramAggregation(String name, JsonObject histogramAggregation) {
    super(name, histogramAggregation);
    if (histogramAggregation.has(String.valueOf(AggregationField.BUCKETS)) && histogramAggregation.get(String.valueOf(AggregationField.BUCKETS)).isJsonArray()) {
      parseBuckets(histogramAggregation.get(String.valueOf(AggregationField.BUCKETS)).getAsJsonArray());
    }
  }
  private void parseBuckets(JsonArray bucketsSource) {
    for (JsonElement bucketv : bucketsSource) {
      JsonObject bucket = bucketv.getAsJsonObject();
      HistogramAggregation.Histogram histogram = new HistogramAggregation.Histogram(bucket, bucket.get(String.valueOf(AggregationField.KEY)).getAsLong(), bucket.get(String.valueOf(AggregationField.DOC_COUNT)).getAsLong());
      histograms.add(histogram);
    }
  }
  public List<HistogramAggregation.Histogram> getBuckets() {
    return histograms;
  }
  public static class Histogram extends Bucket {
    private Long key;
    /*package*/ Histogram(JsonObject bucket, Long key, Long count) {
      super(bucket, count);
      this.key = key;
    }
    public Long getKey() {
      return key;
    }
    @Override
    public boolean equals(Object obj) {
      if (obj == null) {
        return false;
      }
      if (obj == this) {
        return true;
      }
      if (obj.getClass() != getClass()) {
        return false;
      }
      HistogramAggregation.Histogram rhs = (HistogramAggregation.Histogram) obj;
      return new EqualsBuilder().appendSuper(super.equals(obj)).append(key, rhs.key).isEquals();
    }
    @Override
    public int hashCode() {
      return new HashCodeBuilder().appendSuper(super.hashCode()).append(key).toHashCode();
    }
  }
  @Override
  public boolean equals(Object obj) {
    if (obj == null) {
      return false;
    }
    if (obj == this) {
      return true;
    }
    if (obj.getClass() != getClass()) {
      return false;
    }
    HistogramAggregation rhs = (HistogramAggregation) obj;
    return new EqualsBuilder().appendSuper(super.equals(obj)).append(histograms, rhs.histograms).isEquals();
  }
  @Override
  public int hashCode() {
    return new HashCodeBuilder().appendSuper(super.hashCode()).append(histograms).toHashCode();
  }
}
