package io.searchbox.core;

/*Generated by MPS */

import io.searchbox.action.SingleResultAbstractDocumentTargetedAction;
import io.searchbox.action.BulkableAction;
import io.searchbox.action.AbstractDocumentTargetedAction;

public class Delete extends SingleResultAbstractDocumentTargetedAction implements BulkableAction<DocumentResult> {

  protected Delete(Delete.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  @Override
  public String getRestMethodName() {
    return "DELETE";
  }
  @Override
  public String getPathToResult() {
    return "ok";
  }
  @Override
  public String getBulkMethodName() {
    return "delete";
  }


  public static class Builder extends AbstractDocumentTargetedAction.Builder<Delete, Delete.Builder> {
    public Builder(String id) {
      this.id(id);
    }
    public Delete build() {
      return new Delete(this);
    }
  }
}
