package io.searchbox.core;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.EqualsBuilder;
import io.searchbox.action.AbstractMultiTypeActionBuilder;

public class DeleteByQuery extends GenericResultAbstractAction {

  protected DeleteByQuery(DeleteByQuery.Builder builder) {
    super(builder);
    this.payload = builder.query;
    setURI(buildURI());
  }
  @Override
  protected String buildURI() {
    return super.buildURI() + "/_query";
  }
  @Override
  public String getPathToResult() {
    return "ok";
  }
  @Override
  public String getRestMethodName() {
    return "DELETE";
  }
  @Override
  public int hashCode() {
    return new HashCodeBuilder().appendSuper(super.hashCode()).toHashCode();
  }
  @Override
  public boolean equals(Object obj) {
    if (obj == null) {
      return false;
    }
    if (obj == this) {
      return true;
    }
    if (obj.getClass() != getClass()) {
      return false;
    }
    return new EqualsBuilder().appendSuper(super.equals(obj)).isEquals();
  }
  public static class Builder extends AbstractMultiTypeActionBuilder<DeleteByQuery, DeleteByQuery.Builder> {
    private String query;
    public Builder(String query) {
      this.query = query;
    }
    @Override
    public DeleteByQuery build() {
      return new DeleteByQuery(this);
    }
  }
}
