package io.searchbox.core;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.EqualsBuilder;
import io.searchbox.action.AbstractAction;

public class Validate extends GenericResultAbstractAction {

  protected Validate(Validate.Builder builder) {
    super(builder);
    this.indexName = builder.index;
    this.typeName = builder.type;
    this.payload = builder.query;
    setURI(buildURI());
  }
  @Override
  protected String buildURI() {
    return super.buildURI() + "/_validate/query";
  }
  @Override
  public String getRestMethodName() {
    return "POST";
  }
  @Override
  public String getPathToResult() {
    return "valid";
  }
  @Override
  public int hashCode() {
    return new HashCodeBuilder().appendSuper(super.hashCode()).toHashCode();
  }
  @Override
  public boolean equals(Object obj) {
    if (obj == null) {
      return false;
    }
    if (obj == this) {
      return true;
    }
    if (obj.getClass() != getClass()) {
      return false;
    }
    return new EqualsBuilder().appendSuper(super.equals(obj)).isEquals();
  }
  public static class Builder extends AbstractAction.Builder<Validate, Validate.Builder> {
    private final Object query;
    private String index;
    private String type;
    public Builder(Object query) {
      this.query = query;
    }
    public Validate.Builder index(String val) {
      index = val;
      return this;
    }
    public Validate.Builder type(String val) {
      type = val;
      return this;
    }
    public Validate build() {
      return new Validate(this);
    }
  }
}
