package io.searchbox.action;

/*Generated by MPS */

import java.util.Set;
import java.util.LinkedHashSet;
import java.util.Collection;
import org.apache.commons.lang3.StringUtils;

public abstract class AbstractMultiTypeActionBuilder<T extends Action, K> extends AbstractMultiIndexActionBuilder<T, K> {

  private Set<String> indexTypes = new LinkedHashSet<String>();
  public K addType(Collection<? extends String> indexTypes) {
    this.indexTypes.addAll(indexTypes);
    return (K) this;
  }
  public K addType(String indexType) {
    this.indexTypes.add(indexType);
    return (K) this;
  }
  public String getJoinedTypes() {
    return StringUtils.join(indexTypes, ",");
  }
}
