package io.searchbox.action;

/*Generated by MPS */

import io.searchbox.client.JestResult;
import com.google.gson.Gson;
import java.util.Map;

/**
 * @author Dogukan Sonmez
 */
public interface Action<T extends JestResult> {
  public String getURI();
  public String getRestMethodName();
  public String getData(Gson gson);
  public String getPathToResult();
  public Map<String, Object> getHeaders();
  public T createNewElasticSearchResult(String responseBody, int statusCode, String reasonPhrase, Gson gson);
}
