package io.searchbox.action;

/*Generated by MPS */

import io.searchbox.client.JestResult;
import com.google.gson.Gson;

public abstract class GenericResultAbstractDocumentTargetedAction extends AbstractDocumentTargetedAction<JestResult> {

  public GenericResultAbstractDocumentTargetedAction(AbstractDocumentTargetedAction.Builder builder) {
    super(builder);
  }
  @Override
  public JestResult createNewElasticSearchResult(String responseBody, int statusCode, String reasonPhrase, Gson gson) {
    return createNewElasticSearchResult(new JestResult(gson), responseBody, statusCode, reasonPhrase, gson);
  }
}
