package io.searchbox.action;

/*Generated by MPS */

import io.searchbox.core.DocumentResult;
import com.google.gson.Gson;

public abstract class SingleResultAbstractDocumentTargetedAction extends AbstractDocumentTargetedAction<DocumentResult> {

  public SingleResultAbstractDocumentTargetedAction(AbstractDocumentTargetedAction.Builder builder) {
    super(builder);
  }
  @Override
  public DocumentResult createNewElasticSearchResult(String responseBody, int statusCode, String reasonPhrase, Gson gson) {
    return createNewElasticSearchResult(new DocumentResult(gson), responseBody, statusCode, reasonPhrase, gson);
  }
}
