package io.searchbox.indices.aliases;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractMultiIndexActionBuilder;

public class GetAliases extends GenericResultAbstractAction {

  protected GetAliases(GetAliases.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  @Override
  public String getRestMethodName() {
    return "GET";
  }
  @Override
  protected String buildURI() {
    return super.buildURI() + "/_aliases";
  }
  public static class Builder extends AbstractMultiIndexActionBuilder<GetAliases, GetAliases.Builder> {
    @Override
    public GetAliases build() {
      return new GetAliases(this);
    }
  }
}
