package io.searchbox.cluster;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractAction;

public class GetSettings extends GenericResultAbstractAction {

  protected GetSettings(GetSettings.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  protected String buildURI() {
    return super.buildURI() + "/_cluster/settings";
  }
  @Override
  public String getRestMethodName() {
    return "GET";
  }
  public static class Builder extends AbstractAction.Builder<GetSettings, GetSettings.Builder> {
    @Override
    public GetSettings build() {
      return new GetSettings(this);
    }
  }
}
