package io.searchbox.cluster;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractAction;

public class Health extends GenericResultAbstractAction {

  protected Health(Health.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  @Override
  protected String buildURI() {
    return super.buildURI() + "/_cluster/health/";
  }
  @Override
  public String getRestMethodName() {
    return "GET";
  }
  public static class Builder extends AbstractAction.Builder<Health, Health.Builder> {
    @Override
    public Health build() {
      return new Health(this);
    }
  }
}
