package io.searchbox.cluster;

/*Generated by MPS */

import io.searchbox.action.GenericResultAbstractAction;
import io.searchbox.action.AbstractMultiINodeActionBuilder;

public class NodesInfo extends GenericResultAbstractAction {

  protected NodesInfo(NodesInfo.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  protected String buildURI() {
    return super.buildURI() + "/_nodes/" + nodes;
  }
  @Override
  public String getRestMethodName() {
    return "GET";
  }
  @Override
  public String getPathToResult() {
    return "nodes";
  }
  public static class Builder extends AbstractMultiINodeActionBuilder<NodesInfo, NodesInfo.Builder> {
    public NodesInfo.Builder withSettings() {
      return addCleanApiParameter("settings");
    }
    public NodesInfo.Builder withOs() {
      return addCleanApiParameter("os");
    }
    public NodesInfo.Builder withProcess() {
      return addCleanApiParameter("process");
    }
    public NodesInfo.Builder withJvm() {
      return addCleanApiParameter("jvm");
    }
    public NodesInfo.Builder withThreadPool() {
      return addCleanApiParameter("thread_pool");
    }
    public NodesInfo.Builder withNetwork() {
      return addCleanApiParameter("network");
    }
    public NodesInfo.Builder withTransport() {
      return addCleanApiParameter("transport");
    }
    public NodesInfo.Builder withHttp() {
      return addCleanApiParameter("http");
    }
    public NodesInfo.Builder withPlugins() {
      return addCleanApiParameter("plugins");
    }
    @Override
    public NodesInfo build() {
      return new NodesInfo(this);
    }
  }
}
