package com.searchly.jestdroid.http;

/*Generated by MPS */

import org.apache.http.client.methods.HttpEntityEnclosingRequestBaseHC4;
import java.net.URI;
import org.apache.http.client.methods.HttpGet;

public class HttpGetWithEntity extends HttpEntityEnclosingRequestBaseHC4 {

  public HttpGetWithEntity() {
    super();
  }
  public HttpGetWithEntity(URI uri) {
    super();
    setURI(uri);
  }
  public HttpGetWithEntity(String uri) {
    super();
    setURI(URI.create(uri));
  }
  @Override
  public String getMethod() {
    return HttpGet.METHOD_NAME;
  }
}
