package com.searchly.jestdroid.http;

/*Generated by MPS */

import org.apache.http.client.methods.HttpEntityEnclosingRequestBaseHC4;
import java.net.URI;
import org.apache.http.client.methods.HttpDelete;

public class HttpDeleteWithEntity extends HttpEntityEnclosingRequestBaseHC4 {

  public HttpDeleteWithEntity() {
    super();
  }
  public HttpDeleteWithEntity(URI uri) {
    super();
    setURI(uri);
  }
  public HttpDeleteWithEntity(String uri) {
    super();
    setURI(URI.create(uri));
  }
  @Override
  public String getMethod() {
    return HttpDelete.METHOD_NAME;
  }
}
