package io.searchbox.indices.template;

/*Generated by MPS */


public class DeleteTemplate extends TemplateAction {

  protected DeleteTemplate(DeleteTemplate.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  @Override
  public String getRestMethodName() {
    return "DELETE";
  }
  public static class Builder extends TemplateAction.Builder<DeleteTemplate, DeleteTemplate.Builder> {
    public Builder(String template) {
      super(template);
    }
    @Override
    public DeleteTemplate build() {
      return new DeleteTemplate(this);
    }
  }
}
