package io.searchbox.indices.script;

/*Generated by MPS */


public class DeleteIndexedScript extends AbstractIndexedScript {

  protected DeleteIndexedScript(DeleteIndexedScript.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  @Override
  public String getRestMethodName() {
    return "DELETE";
  }
  public static class Builder extends AbstractIndexedScript.Builder<DeleteIndexedScript, DeleteIndexedScript.Builder> {
    public Builder(String scriptName) {
      super(scriptName);
    }
    @Override
    public DeleteIndexedScript build() {
      return new DeleteIndexedScript(this);
    }
  }
}
