package io.searchbox.indices.script;

/*Generated by MPS */


public class GetIndexedScript extends AbstractIndexedScript {

  protected GetIndexedScript(GetIndexedScript.Builder builder) {
    super(builder);
    setURI(buildURI());
  }
  @Override
  public String getRestMethodName() {
    return "GET";
  }
  public static class Builder extends AbstractIndexedScript.Builder<GetIndexedScript, GetIndexedScript.Builder> {
    public Builder(String scriptName) {
      super(scriptName);
    }
    @Override
    public GetIndexedScript build() {
      return new GetIndexedScript(this);
    }
  }
}
