package io.searchbox.indices.script;

/*Generated by MPS */


public enum ScriptLanguage {
  GROOVY("groovy"),
  EXPRESSION("expression"),
  MUSTACHE("mustache"),
  MVEL("mvel"),
  JAVASCRIPT("javascript"),
  PYTHON("python");

  public final String pathParameterName;

  ScriptLanguage(String pathParameterName) {
    this.pathParameterName = pathParameterName;
  }
}
